### ISSUE TITLE
I do not see a HUD

### ISSUE THREAD

**Issue by timmolter** [michaelochs/BCScanner#13]
Is there supposed to be a HUD? I don't see any. It'd be nice to have. I see a HUD referenced in the code. How do I enable it?

**Comment by timmolter** [comment]
Additional information: I forked the project and followed the instructions to get the example working. If I tap 'scan' I see the HUD. If I tap 'Scan Modal', I don't see any HUD. Any ideas why it's not working?

**Comment by michaelochs** [comment]
Hi! Sorry for the delay. I am currently out of town. There is a delegate method that you need to implement that returns an image that is used as the hud image.

The modal sample probably does not implement this method, I'll look into that when I am back home.

However if this behavior is not what you expect, feel free to file an issue and explain how you would expect the api.

**Comment by timmolter** [comment]
Yesterday I looked into adding the HUD to the `scan modal` view, but I couldn't figure it out. I tried various things for about two hours and gave up. I'm not an Objective-C expert, and that's probably the problem. Adding this feature would be greatly appreciated!

**Comment by michaelochs** [comment]
To be clear here, by 'scan modal view' you mean the use of the `bcscanner_presentScannerWithCodeTypes:completionHandler:` method?

I added issue #17 for this. I do not know if I have the time to implement it this week, but I definitely try to add this feature at the weekend.

**Comment by timmolter** [comment]
Yes, that is correct. Thanks, much appreciated! Great project!

**Comment by michaelochs** [comment]
I implemented this in PR #19. If you like, please have a look at this PR and check if this is what you expect from the API. If you have any comments or suggestions feel free to post them in the PR.

**Comment by timmolter** [comment]
I tried your PR and it works. Looks great! Please merge.
