### ISSUE TITLE
HUD image should be available when using the block based api

### ISSUE THREAD

**Issue by michaelochs** [michaelochs/BCScanner#17]
It should be possible to specify the hud image that should be used when using the block based api.

**Comment by timmolter** [comment]
I have no idea why, but I don't see the HUD anymore. I'm pretty sure it was working before though. Any ideas?

**Comment by timmolter** [comment]
Nevermind. It does work on the example app, just not in my app. Must be my fault...

**Comment by michaelochs** [comment]
Please note that you need to add the image to your apps bundle if you want to need the one from the sample app.
